name: Lint, Test, Build

on: [push, pull_request] # Runs when code is pushed or a PR is created

jobs:
  lint_test_build:
    runs-on: ubuntu-latest # Runner (machine) provided by GitHub

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Linter
      - name: Run Lint
        run: npm run lint

      # Step 5: Run Tests
      - name: Run Tests
        run: npm test

      # Step 6: Build Project
      - name: Build Project
        run: npm run build
